name: Push docs

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  mkdocs-build-and-push:
    name: mkdocs and push to docs.donkeycar.com
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install docs dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install mkdocs mkdocs-redirects mkdocs-material

      - name: Build and deploy docs
        run: |
          python -m mkdocs gh-deploy --force -v
          echo "Docs were made and pushed to docs.donkeycar.com"
